package com.imooc.pojo;

import java.util.Date;

public class UsersReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.deal_user_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String dealUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.deal_video_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String dealVideoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.title
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.content
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.userid
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_report.create_date
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.id
     *
     * @return the value of users_report.id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.id
     *
     * @param id the value for users_report.id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.deal_user_id
     *
     * @return the value of users_report.deal_user_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getDealUserId() {
        return dealUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.deal_user_id
     *
     * @param dealUserId the value for users_report.deal_user_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setDealUserId(String dealUserId) {
        this.dealUserId = dealUserId == null ? null : dealUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.deal_video_id
     *
     * @return the value of users_report.deal_video_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getDealVideoId() {
        return dealVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.deal_video_id
     *
     * @param dealVideoId the value for users_report.deal_video_id
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setDealVideoId(String dealVideoId) {
        this.dealVideoId = dealVideoId == null ? null : dealVideoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.title
     *
     * @return the value of users_report.title
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.title
     *
     * @param title the value for users_report.title
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.content
     *
     * @return the value of users_report.content
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.content
     *
     * @param content the value for users_report.content
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.userid
     *
     * @return the value of users_report.userid
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.userid
     *
     * @param userid the value for users_report.userid
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_report.create_date
     *
     * @return the value of users_report.create_date
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_report.create_date
     *
     * @param createDate the value for users_report.create_date
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}