package com.imooc.mapper;

import java.util.List;

import com.imooc.pojo.Bgm;
import com.imooc.pojo.BgmExample;
import org.apache.ibatis.annotations.Param;

public interface BgmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int countByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int deleteByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int insert(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int insertSelective(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    List<Bgm> selectByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    Bgm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bgm record, @Param("example") BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByExample(@Param("record") Bgm record, @Param("example") BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByPrimaryKeySelective(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByPrimaryKey(Bgm record);
}