package com.imooc.mapper;

import com.imooc.pojo.Videos;
import com.imooc.pojo.VideosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int countByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int deleteByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int insert(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int insertSelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    List<Videos> selectByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    Videos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByExample(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByPrimaryKeySelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated Wed Dec 11 12:15:47 CST 2019
     */
    int updateByPrimaryKey(Videos record);
}